### ISSUE TITLE
Support for 64bit adiirc

### ISSUE THREAD

**Issue by SReject** [Kedyn/SimpleJScripts#1]
~You can support adiirc 64bit easily enough in your code by instructing users to download [tsc64.dll](https://github.com/tablacus/TablacusScriptControl) and having them comreg it via `/comreg "path\to\tsc64.dll"`~

Update: The installation has changed, Download the [tsc64_1101.cab](https://github.com/tablacus/TablacusScriptControl/releases/tag/1.1.0.1) asset, extract, and run setup.exe

Once done, you only need to add one line to your `$jsCreate()` alias:

```mirc-script
alias jsCreate {
  ; ...

      if (!$~com(%name)) {
        .!comopen %name MSScriptControl.ScriptControl

        ; This line will attempt to create a scriptcontrol using tsc64.dll
        if ($~comerr) .!comopen %name Tablacus.ScriptControl

        if (!$~comerr) !return $~com(%name,language,4,bstr,jscript)
      }
  ; ...
}
```

**Comment by Kedyn** [comment]
Thank you for your input.

I have downloaded and installed adiirc (64 bit), I have also downloaded tsc64.dll. Unfortunately I keep getting the following error: `* /comreg: Unable to register Com '...\tsc64.dll'`. I will continue to get this to work, any help is greatly appreciated.

**Comment by SReject** [comment]
Oops, it seems he has changed the install process; you do not need to use `/comreg`

1. Download the [tsc64_1101.cab](https://github.com/tablacus/TablacusScriptControl/releases/tag/1.1.0.1) asset
2. extract the cab
3. run setup.exe

From there, my example should work

**Comment by SReject** [comment]
Updated OP to use name-spaced progid, instead of just the resource name

**Comment by Kedyn** [comment]
Thank you so much for your help, everything is working now and I have updated the script.
